### ISSUE TITLE
[Backlog] Users model 생성

### ISSUE THREAD

**Issue by kingwangzzang1234** [team-f9/fluffy-guide#1]
## Description

 Users 모델을 초기화합니다.

필요한 필드

```python
users = {
    'name':'',
    'age':'',
}
```

## Tasks

- [x] 유저 모델 생성
- [x] 유저 모델 작성
- [ ] 유저 모델 적용

## References

- [google](https://www.google.com/)
